[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.20.0"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
